# Generated by Django 5.0.2 on 2024-02-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_playlist_user_profile_delete_muser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Альбом'),
        ),
        migrations.AlterField(
            model_name='song',
            name='album_cover_url',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Обложка альбома'),
        ),
        migrations.AlterField(
            model_name='song',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='song',
            name='bitrate',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='BitRate'),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Длительность сек.'),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Длительность'),
        ),
    ]
