# Generated by Django 5.0.2 on 2024-02-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_song_album_alter_song_album_cover_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='url',
            field=models.CharField(max_length=250, unique=True, verbose_name='URL песни'),
        ),
    ]
