# Generated by Django 5.0.2 on 2024-02-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_song_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='url',
            field=models.CharField(max_length=250, verbose_name='URL песни'),
        ),
    ]
