# Generated by Django 5.0.2 on 2024-03-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_song_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(blank=True, null=True, to='main.song', verbose_name='Песни'),
        ),
    ]
